// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using backend_dotnet_r06_mall.Data;

namespace backend_dotnet_r06_mall.Migrations
{
    [DbContext(typeof(BanHangContext))]
    [Migration("20211221114442_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.13")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("backend_dotnet_r06_mall.Models.CuaHang", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DanhGia")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MoTa")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("SDT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("STK")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("TenCuaHang")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("CuaHang_");
                });

            modelBuilder.Entity("backend_dotnet_r06_mall.Models.DonHang", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DanhGia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("HinhThucThanhToanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("KhachHangId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("NguoiGiaoHangId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<DateTime>("ThoiGian")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("TinhTrangDonHangId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("TinhTrangThanhToan")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("HinhThucThanhToanId");

                    b.HasIndex("KhachHangId");

                    b.HasIndex("NguoiGiaoHangId");

                    b.HasIndex("TinhTrangDonHangId");

                    b.ToTable("DonHang_");
                });

            modelBuilder.Entity("backend_dotnet_r06_mall.Models.HinhThucThanhToan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TenHTTT")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("HinhThucThanhToan_");
                });

            modelBuilder.Entity("backend_dotnet_r06_mall.Models.KetQuaKiemTra", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("KetQua")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("NgayKiemTra")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("NguoiGiaoHangId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("NguoiGiaoHangId");

                    b.ToTable("KetQuaKiemTra_");
                });

            modelBuilder.Entity("backend_dotnet_r06_mall.Models.KhachHang", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Cccd")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<string>("DiaChi")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SDT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("STK")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("TenKhachHang")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Vung")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("KhachHang_");
                });

            modelBuilder.Entity("backend_dotnet_r06_mall.Models.LoaiSanPham", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Ten")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("LoaiSanPham_");
                });

            modelBuilder.Entity("backend_dotnet_r06_mall.Models.NguoiGiaoHang", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Cccd")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<string>("DiaChi")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayDangKy")
                        .HasColumnType("datetime2");

                    b.Property<string>("STK")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("SoDienThoai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenNguoiGiaoHang")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid?>("TinhTrangDonHangId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("VungHoatDong")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("TinhTrangDonHangId");

                    b.ToTable("NguoiGiaoHang_");
                });

            modelBuilder.Entity("backend_dotnet_r06_mall.Models.SanPham", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CuaHangId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DonGia")
                        .HasColumnType("int");

                    b.Property<int>("DonVi")
                        .HasColumnType("int");

                    b.Property<Guid?>("LoaiSanPhamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenSanPham")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("TonKho")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CuaHangId");

                    b.HasIndex("LoaiSanPhamId");

                    b.ToTable("SanPham_");
                });

            modelBuilder.Entity("backend_dotnet_r06_mall.Models.ThongTinDiDuong", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("NgayCap")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayHetHan")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("NguoiGiaoHangId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("NguoiGiaoHangId");

                    b.ToTable("ThongTinDiDuong_");
                });

            modelBuilder.Entity("backend_dotnet_r06_mall.Models.TinhTrangDonHang", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TenTinhTrang")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("TinhTrangDonHang_");
                });

            modelBuilder.Entity("backend_dotnet_r06_mall.Models.DonHang", b =>
                {
                    b.HasOne("backend_dotnet_r06_mall.Models.HinhThucThanhToan", "HinhThucThanhToan")
                        .WithMany()
                        .HasForeignKey("HinhThucThanhToanId");

                    b.HasOne("backend_dotnet_r06_mall.Models.KhachHang", "KhachHang")
                        .WithMany()
                        .HasForeignKey("KhachHangId");

                    b.HasOne("backend_dotnet_r06_mall.Models.NguoiGiaoHang", "NguoiGiaoHang")
                        .WithMany("DonHang")
                        .HasForeignKey("NguoiGiaoHangId");

                    b.HasOne("backend_dotnet_r06_mall.Models.TinhTrangDonHang", "TinhTrangDonHang")
                        .WithMany()
                        .HasForeignKey("TinhTrangDonHangId");

                    b.Navigation("HinhThucThanhToan");

                    b.Navigation("KhachHang");

                    b.Navigation("NguoiGiaoHang");

                    b.Navigation("TinhTrangDonHang");
                });

            modelBuilder.Entity("backend_dotnet_r06_mall.Models.KetQuaKiemTra", b =>
                {
                    b.HasOne("backend_dotnet_r06_mall.Models.NguoiGiaoHang", null)
                        .WithMany("KetQuaKiemTra")
                        .HasForeignKey("NguoiGiaoHangId");
                });

            modelBuilder.Entity("backend_dotnet_r06_mall.Models.NguoiGiaoHang", b =>
                {
                    b.HasOne("backend_dotnet_r06_mall.Models.TinhTrangDonHang", "TinhTrangDonHang")
                        .WithMany()
                        .HasForeignKey("TinhTrangDonHangId");

                    b.Navigation("TinhTrangDonHang");
                });

            modelBuilder.Entity("backend_dotnet_r06_mall.Models.SanPham", b =>
                {
                    b.HasOne("backend_dotnet_r06_mall.Models.CuaHang", "CuaHang")
                        .WithMany()
                        .HasForeignKey("CuaHangId");

                    b.HasOne("backend_dotnet_r06_mall.Models.LoaiSanPham", "LoaiSanPham")
                        .WithMany()
                        .HasForeignKey("LoaiSanPhamId");

                    b.Navigation("CuaHang");

                    b.Navigation("LoaiSanPham");
                });

            modelBuilder.Entity("backend_dotnet_r06_mall.Models.ThongTinDiDuong", b =>
                {
                    b.HasOne("backend_dotnet_r06_mall.Models.NguoiGiaoHang", null)
                        .WithMany("ThongTinDiDuong")
                        .HasForeignKey("NguoiGiaoHangId");
                });

            modelBuilder.Entity("backend_dotnet_r06_mall.Models.NguoiGiaoHang", b =>
                {
                    b.Navigation("DonHang");

                    b.Navigation("KetQuaKiemTra");

                    b.Navigation("ThongTinDiDuong");
                });
#pragma warning restore 612, 618
        }
    }
}
